<?php
/**
 * Created by PhpStorm.
 * User: Anonymou_Chen
 * Date: 2017/3/6
 * Time: 19:09
 */
namespace  App;
use Illuminate\Database\Eloquent\Model;

class Student extends Model{

    const SEX_UN = 10; //未知
    const SEX_MAN = 20;  //男
    const  SEX_WOMAN = 30; //女


    protected $table = 'student';
    public  $timestamps = true ;
    protected $fillable = ['name','age','sex'];

    protected  function  getDateFormat()
    {
        return time(); // TODO: Change the autogenerated stub
    }

    protected  function asDateTime($var)
    {
        return $var; // TODO: Change the autogenerated stub
    }

    //将输入的数字转换为性别的方法
    public function  sex( $ind=null ){
        $arr = [

            self::SEX_UN => '未知',
            self::SEX_MAN=>'男',
            self::SEX_WOMAN=>'女',
        ];

        if ($ind !== null){
            return array_key_exists($ind,$arr) ? $arr[$ind]:$arr[self::SEX_UN];
        }
        return $arr;
    }

}