<?php
/**
 * Created by PhpStorm.
 * User: Anonymou_Chen
 * Date: 2017/3/6
 * Time: 19:09
 */
namespace  App;
use Illuminate\Database\Eloquent\Model;

class Student extends Model{

    protected $table = 'student';
    public  $timestamps = true ;
    protected $fillable = ['name','age','sex'];

    protected  function  getDateFormat()
    {
        return time(); // TODO: Change the autogenerated stub
    }

    protected  function asDateTime($var)
    {
        return $var; // TODO: Change the autogenerated stub
    }

}